### ISSUE TITLE
Optimize the errors so that it also works when there are warnings present in the array

### ISSUE THREAD

**Issue by sebastienhenau** [oSoc15/dcat-validator#8]

**Comment by coreation** [comment]
@sebastienhenau Use the title of the issue as a summary, to the point sentence. Then use the description to elaborate. This title for example is way too long and I sorta have to guess as to what you mean, convert to something like this:

Optimize the errors in the front-end.


Currently the warnings that are returned from the validator are not picked up by the front-end javascript, they also need to be listed, preferably under the error list.

**Comment by sebastienhenau** [comment]
Fixed this issue, warnings and errors are now shown together
